### PR TITLE
#325 fix CircuitBreaker isFailure logic on HalfOpen state (ZIO1)

### PR DESCRIPTION
**Pull request by vagroz**
Solve #325. Use `isFailure` on the HalfOpen state too.

### CODE REVIEW

**Comment by svroonland** [comment]
Thanks, the implementation looks good and it's nice to have unit test coverage.

Would be it be a lot of trouble for you to write the tests without zio mocks? That's a piece of the tech stack I'd rather not add to this library and maintain in the future.

**Comment by vagroz** [comment]
Ok, I'll rewrite)

**Comment by vagroz** [comment]
I seems `FailureRateTrippingStrategySpec` is flacky because it uses live clock. Could you re-run tests, please?

**Review by svroonland — APPROVED** [review]

**Comment by svroonland** [comment]
Thanks! I'll make a new release shortly

**Pull request merged**
